version: '3'
services:
  app:
    container_name: "rest-calculator"
    image:
      rest-calculator:latest
    build: .
    links:
      - redis
      - mongo
    ports:
      - 8080:8080
      
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: operation
    depends_on:
      - mongo
      - redis
  mongo:
    image:
      mongo
    ports:
      - 27017:27017
    restart: always 
#    environment:
#         MONGO_INITDB_ROOT_USERNAME: root
#         MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./data/db:/data/db
    hostname: 
      -mongo
  redis:
    image: redis
    volumes:
      - ./data/redis:/data/db
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    hostname: 
      -redis
