version: '3'
services:
  api:
    build:
      .
    image:
      rest-calculator:latest
    ports:
      - 8080:8080
    depends_on:
      - mongo-db
      - redis
    environment:
      - SPRING_DATA_MONGODB_HOST=localhost
      - MONGODB_HOST=localhost
  mongo-db:
    image:
      mongo:3.0.12
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    hostname: mongo
  redis:
    container_name: redis
    image: redis
    hostname: redis
    ports:
      - 6379:6379

