version: '3.8'
services:
  api:
    build:
      .
    image:
      rest-calculator:latest
    ports:
      - 8080:8080
    depends_on:
      - mongo-db
      - redis
    container_name: "rest-calculator"
  mongo-db:
    image:
      mongo:latest
    container_name: "mymongodb"
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  redis:
    image: redis
    volumes:
      - ./data/redis:/data/db
    ports:
      - 6379:6379
